
<font color =#0984e3  size = 10 face="Verdana">
Numpy
    </font>
    <font color =#2d3436  size = 3>
 <br><br>-为Python提供强大的数组 与 向量运算
        </font>


In [1]:
import numpy as np

#### 将python内置的list转换为**numpy array**

In [2]:
py_arr = [1,2,3]
print(py_arr)
print(type(py_arr))

[1, 2, 3]
<class 'list'>


In [3]:
np_arr = np.array(py_arr)
#打印numpy arr
print(np_arr)
#查看numpy arr的类型
print(type(np_arr))
#查看numpy arr里元素的类型
print(type(np_arr[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int32'>


## dtype  
在创建numpy array的时候可以多添加一个参数，如下  
```py
np_arr = np.array(py_arr, dtype = np.float64)
```


In [4]:
np_arr = np.array(py_arr, dtype = np.float64)
#打印numpy arr
print(np_arr)
#查看numpy arr的类型
print(type(np_arr))
#查看numpy arr里元素的类型
print(type(np_arr[0]))



[1. 2. 3.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


<div style='background-color:  #c8d6e5'>
    <br>
    </div>

In [5]:
#也可以转换tuple
np.array((1,2,3))

array([1, 2, 3])

- numpy array中只能储存相同类型的元素

```
np.array([1,2,3,4,True,False])
np.array([1,2,3,'numpy'])
```
布尔True = 1
布尔False = 0

In [6]:
np.array([1,2,3,4,True,False])

array([1, 2, 3, 4, 1, 0])

#### 因为出现了String类型， 所以numpy数组中所有元素类型全部变成了String

In [7]:
np.array([1,2,3,'numpy',True])

array(['1', '2', '3', 'numpy', 'True'], dtype='<U11')

<div style='background-color: #c8d6e5'>
    <br>
    </div>
    
    
### numpy的一些基本函数

*Note:*   
可以在结尾处 加入参数  
`dtype = np.float`   
来指定array的类型

In [8]:
#生成5 row 1  column的 o
np.zeros((5,1)) 

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [9]:
#生成 3 row, 2 column的1
np.ones((3,2), dtype=np.int) 

array([[1, 1],
       [1, 1],
       [1, 1]])

In [10]:
# 生成 5 row, 3 column的3
np.tile(3,(5,3))

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [11]:
np.tile(np.arange(10), (3,1))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
#重复 array  或 tuple中的元素进行重复
np.repeat((5, 6),4)

array([5, 5, 5, 5, 6, 6, 6, 6])

---

In [13]:
#从0开始 总共生成10个数
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#从1 到 5 之前取10个数
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

#### 可以通过`np.matrix('1, 2 ; 3, 4')`  来创建矩阵



In [15]:
np.matrix('1,2;3,4')

matrix([[1, 2],
        [3, 4]])


但是一般不使用这种方法， 通常情况下还是使用  
`np.array([[1,2],[3,4]])`  
这种方法  
你也可以使用  
`np.array([1,2,3,4]).reshape(2,2)`  
来达到同样的效果

************
<div style= 'background-color:PapayaWhip'>
<font color =LightCoral size = 3>并不知道有什么卵用的代码,<br>建议直接无视</font>
</div>

In [16]:
x = np.array([('a' , 0.8), ('b', 0.2),('c', 0.3)], dtype=[('label', 'a8'), ('prob', 'f8')])

In [17]:
x['label']

array([b'a', b'b', b'c'], dtype='|S8')

In [18]:
x['prob']

array([0.8, 0.2, 0.3])

<div style='background-color: PapayaWhip'>
    <font size=4 color = #222f3e>=============================================================================================
        </font>
</div>



<div style="background-color:#ecf0f1;">
 <font color = #2c3e50 size = 5 face="Verdana">
     <br>
     Numpy的运算(intro)
     <br>
     <br>
    </font>
</div>

#### Numpy多维运算支持broadcasting!
- 两者的shape必须相同
- 或者其中一者 shape是 **1**


In [19]:
a = np.array([2,4,6])
b = np.array([8,10,12])

In [20]:
a+b

array([10, 14, 18])

In [21]:
a+1

array([3, 5, 7])

In [22]:
a*b

array([16, 40, 72])

In [23]:
5 -b

array([-3, -5, -7])

In [24]:
a = np.arange(20).reshape(20,1)
b = np.arange(100).reshape(20,5)

<div style= "background-color: #f1f2f6;">
<font size = 3 face= face='Verdana'>首先它们row是相等的都是20 <br>然后其中有一列是1
</div>

In [25]:
a + b

array([[  0,   1,   2,   3,   4],
       [  6,   7,   8,   9,  10],
       [ 12,  13,  14,  15,  16],
       [ 18,  19,  20,  21,  22],
       [ 24,  25,  26,  27,  28],
       [ 30,  31,  32,  33,  34],
       [ 36,  37,  38,  39,  40],
       [ 42,  43,  44,  45,  46],
       [ 48,  49,  50,  51,  52],
       [ 54,  55,  56,  57,  58],
       [ 60,  61,  62,  63,  64],
       [ 66,  67,  68,  69,  70],
       [ 72,  73,  74,  75,  76],
       [ 78,  79,  80,  81,  82],
       [ 84,  85,  86,  87,  88],
       [ 90,  91,  92,  93,  94],
       [ 96,  97,  98,  99, 100],
       [102, 103, 104, 105, 106],
       [108, 109, 110, 111, 112],
       [114, 115, 116, 117, 118]])

<font size = 4 color=#2f3542 face="黑体">下方代码原理一样 要么是相等 要么两者其中有一个是1所以可以相加<br>
</font>
```py
a = np.ones((9,8,1,3,3))
b = np.ones((1,8,9,1,3))
```


<div style="background-color:#ecf0f1;">
 <font color = #2c3e50 size = 5 face="Verdana">
     <br>
     Numpy Array的切片
     <br>
     <br>
    </font>
</div>

*为了方便观察我为下面两个array分别加了`3` 和 `5`*

In [26]:
a = np.arange(20).reshape(20,1)+3
b = np.arange(100).reshape(20,5)+5


```py
a.shape
>>>(20,1)

b.shape
>>>(20,5)
```

- 可以像普通list 或者tuple一样通过索引获取其中的一个值

In [27]:
print("a里的第6个数是: ",a[5])

a里的第6个数是:  [8]


#### 为什么这里打印出来的还是一个list呢

因为`a`是一个二维的array
通过 `.ndim`来查看这是一个几维数组


```py
print(a.ndim,"dimentions")
>>> 2 dimentions
```


这时如果我们把a 变成**一维**的话一切就正常了

In [28]:
#降维打击
new_a1 = a.reshape(20) #方法1
new_a2 = a.flatten() #方法2

<font size = 3 color = #ee5253 face = '黑体'>两个方法的结果都是相同</font>
- 这个方法是对比的所有元素
```py
new_a1 == new_a2
>>> array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])
```

- `.all()`这个方法是对比整体
```py
new_a1.all() == new_a2.all()
>>> True
```

- `.any()`的意思是只有两者中有一个相等的话就直接返回`True`
```py
new_a1.any() == new_a2.any()
>>> True
```

------------------

### 但是每次这样做太麻烦了
多维数组的索引是这样的, 就拿`b`作为例子  <br>
#### 首先用`reshape()`把`b`变成一个三维 *tensor*  方便讲解
`new_b = b.reshape(5,5,4)`  

注意观察 
1. b 的原始shape 是`(20,5)`
<br>$20*5=100$
2. new_b的shape是`(5,5,4)` 
<br>$5 * 5 * 4 =100$  

<font size=3 color = #ee5253>tuple内的元素的乘积必须要相等 才能reshape</font>

<font size=3 color =#273c75 >顺便提一个概念 <br>所有操作的前提是这个object是个numpy array<br><br>
    `1`这是一个*scalar*<br>
    `[1]`这是一个*vector*<br>
    `[[1]]`但是这样就是一个matrix了 不过只有1row<br>
    `[ [1] , [1] ]`这是一个*matrix*<br></font>
    
这个是一个**3D tensor**
```py
[[[1., 1.],
  [1., 1.]],
 [[1., 1.],
  [1., 1.]]]
```
*************

In [29]:
new_b = b.reshape(5,5,4)
print(new_b)

[[[  5   6   7   8]
  [  9  10  11  12]
  [ 13  14  15  16]
  [ 17  18  19  20]
  [ 21  22  23  24]]

 [[ 25  26  27  28]
  [ 29  30  31  32]
  [ 33  34  35  36]
  [ 37  38  39  40]
  [ 41  42  43  44]]

 [[ 45  46  47  48]
  [ 49  50  51  52]
  [ 53  54  55  56]
  [ 57  58  59  60]
  [ 61  62  63  64]]

 [[ 65  66  67  68]
  [ 69  70  71  72]
  [ 73  74  75  76]
  [ 77  78  79  80]
  [ 81  82  83  84]]

 [[ 85  86  87  88]
  [ 89  90  91  92]
  [ 93  94  95  96]
  [ 97  98  99 100]
  [101 102 103 104]]]


<div style = 'background-color: #7f8fa6'>
    <br>
</div>


`arr[a,b,c]`


In [30]:
#推荐这个
print(new_b[1,2,3])
#其实也可以这样
print(new_b[1][2][3])

36
36


- `a:b`可以表示从index `a`到`b`之前，如果单`:`则表示这个维的所有元素<br>
- `-1`则表示倒数第一个， 那么`:-3`表示倒数第三个之前的所有元素
```py
new_b[ 0 , : , 2 ]
>>> array([ 7, 11, 15, 19, 23])
```

获取第一个*matirx*的**所有** *vector*的第三个*scalar*